# Generated by Django 3.1.3 on 2022-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_validateimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='validateimages',
            name='right',
            field=models.CharField(default='-2', max_length=9),
        ),
    ]
