# Generated by Django 3.1.3 on 2022-06-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_validateimages_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_uuid', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=64)),
                ('length', models.IntegerField()),
                ('imgurls', models.TextField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '历史记录',
                'verbose_name_plural': '历史记录',
                'db_table': 'historyrecord',
            },
        ),
    ]
