# Generated by Django 3.1.3 on 2022-06-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='pro_length',
            field=models.IntegerField(default=0),
        ),
    ]
