# Generated by Django 3.1.3 on 2022-06-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_history_pro_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(max_length=32)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': '反馈表',
                'verbose_name_plural': '反馈表',
                'db_table': 'feedback',
            },
        ),
    ]
